<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/1/3
 * Time: 13:44
 */

namespace app\components;


use yii\base\Component;

class Player extends Component{
    public $name;
    public function __construct(array $config) {
        parent::__construct($config);
    }
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

}